/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "Database": {
      "host": string
      "name": string
      "password": string
      "type": "sst.sst.Linkable"
      "user": string
    }
  }
}

import "sst"
export {}