/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "DISCORD_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "host": string
      "name": string
      "password": string
      "type": "sst.sst.Linkable"
      "user": string
    }
    "POLAR_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Urls": {
      "api": string
      "auth": string
      "openapi": string
      "site": string
      "type": "sst.sst.Linkable"
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "Auth": cloudflare.Service
    "AuthStorage": cloudflare.KVNamespace
  }
}

import "sst"
export {}